user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
	worker_connections 768;
}

http {

	##
	# Basic Settings
	##

	sendfile on;
	tcp_nopush on;
	tcp_nodelay on;
	keepalive_timeout 65;
	types_hash_max_size 2048;
    client_max_body_size 0;

	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	##
	# SSL Settings
	##

	ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
	ssl_prefer_server_ciphers on;

	##
	# Logging Settings
	##

	log_format main '$remote_addr - $remote_user [$time_local] "$request" $status $bytes_sent "$http_referer" "$http_user_agent" "$gzip_ratio" $request_time';
	access_log /var/log/nginx/access.log;
	error_log /var/log/nginx/error.log;

	##
	# Gzip Settings
	##

	gzip on;
	gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

	##
	# Proxy Cache for S3 image proxying
	##

	proxy_cache_path /var/cache/nginx/s3_images levels=1:2 keys_zone=s3_images:10m
	                 max_size=500m inactive=30d use_temp_path=off;

	##
	# Virtual Host Configs
	##

	include /etc/nginx/conf.d/*.conf;
	include /etc/nginx/sites-enabled/*;

	server {

        listen 80;
	    listen 443 ssl default_server;

	    server_name _;

   	    ssl_certificate /etc/letsencrypt/live/bordercore.com/fullchain.pem;
	    ssl_certificate_key /etc/letsencrypt/live/bordercore.com/privkey.pem;

	    access_log /var/log/nginx/access_default.log;
	    error_log /var/log/nginx/error_default.log;

	    return 403;

	}

}
