"""
URL configuration for the Drill app.
"""

from django.urls import path

from . import views

app_name = "drill"

urlpatterns = [
    path(
        route="",
        view=views.DrillListView.as_view(),
        name="list"
    ),
    path(
        route="question/delete/<uuid:uuid>/",
        view=views.QuestionDeleteView.as_view(),
        name="delete"
    ),
    path(
        route="question/<uuid:uuid>/",
        view=views.QuestionDetailView.as_view(),
        name="detail"
    ),
    path(
        route="question/add/<str:tag>/",
        view=views.QuestionCreateView.as_view(),
        name="add_with_tag"
    ),
    path(
        route="question/add/",
        view=views.QuestionCreateView.as_view(),
        name="add"
    ),
    path(
        route="question/update/<uuid:uuid>/",
        view=views.QuestionUpdateView.as_view(),
        name="update"
    ),
    path(
        route="mutate_is_favorite/",
        view=views.is_favorite_mutate,
        name="is_favorite_mutate"
    ),
    path(
        route="response/<uuid:uuid>/<str:response>/",
        view=views.record_response,
        name="record_response"
    ),
    path(
        route="start_study_session",
        view=views.start_study_session,
        name="start_study_session"
    ),
    path(
        route="study",
        view=views.get_next_question,
        name="study"
    ),
    path(
        route="resume",
        view=views.get_current_question,
        name="resume"
    ),
    path(
        route="get_pinned_tags",
        view=views.get_pinned_tags,
        name="get_pinned_tags"
    ),
    path(
        route="pin_tag",
        view=views.pin_tag,
        name="pin_tag"
    ),
    path(
        route="unpin_tag",
        view=views.unpin_tag,
        name="unpin_tag"
    ),
    path(
        route="sort_pinned_tags",
        view=views.sort_pinned_tags,
        name="sort_pinned_tags"
    ),
    path(
        route="get_disabled_tags",
        view=views.get_disabled_tags,
        name="get_disabled_tags"
    ),
    path(
        route="disable_tag",
        view=views.disable_tag,
        name="disable_tag"
    ),
    path(
        route="enable_tag",
        view=views.enable_tag,
        name="enable_tag"
    ),
    path(
        route="get_title_from_url",
        view=views.get_title_from_url,
        name="get_title_from_url"
    ),
    path(
        route="related_objects/<uuid:uuid>",
        view=views.get_related_objects,
        name="related_objects"
    ),
]
