# Generated by Django 5.2.14 on 2026-06-09 20:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quote", "0003_quote_is_favorite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
