# Generated by Django 5.2.11 on 2026-03-08 15:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tag", "0020_replace_unique_together_with_constraints"),
        ("todo", "0015_alter_todo_priority"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todo",
            options={},
        ),
        migrations.AddIndex(
            model_name="todo",
            index=models.Index(
                fields=["user", "-created"], name="todo_todo_user_id_875bf0_idx"
            ),
        ),
    ]
