# Generated by Django 5.2.11 on 2026-03-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0016_alter_todo_options_todo_todo_todo_user_id_875bf0_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="data",
            field=models.JSONField(
                blank=True,
                help_text="Arbitrary JSON metadata attached to this todo",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="todo",
            name="priority",
            field=models.IntegerField(
                choices=[(1, "High"), (2, "Medium"), (3, "Low")],
                default=3,
                help_text="1=High, 2=Medium, 3=Low",
            ),
        ),
    ]
