# Generated by Django 5.2.8 on 2025-11-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmark", "0010_bookmark_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmark",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
