# Generated by Django 5.2.11 on 2026-03-08 15:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmark", "0011_alter_bookmark_note"),
        ("tag", "0020_replace_unique_together_with_constraints"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookmark",
            options={},
        ),
        migrations.AddIndex(
            model_name="bookmark",
            index=models.Index(
                fields=["user", "-created"], name="bookmark_bo_user_id_8e3de0_idx"
            ),
        ),
    ]
