# Generated by Django 5.2.11 on 2026-03-08 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookmark", "0012_alter_bookmark_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookmark",
            options={"ordering": ("-modified", "-created")},
        ),
    ]
