# Generated by Django 5.2.11 on 2026-03-08 18:19

import bookmark.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmark", "0013_alter_bookmark_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmark",
            name="daily",
            field=bookmark.models.DailyBookmarkJSONField(
                blank=True,
                help_text="Tracks daily viewing status for recurring bookmarks",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bookmark",
            name="data",
            field=models.JSONField(
                blank=True,
                help_text="Extra metadata (e.g. video_duration for YouTube bookmarks)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bookmark",
            name="importance",
            field=models.IntegerField(
                default=1, help_text="Search ranking boost (higher = more prominent)"
            ),
        ),
        migrations.AlterField(
            model_name="bookmark",
            name="is_pinned",
            field=models.BooleanField(
                default=False, help_text="Pinned bookmarks appear at the top of lists"
            ),
        ),
        migrations.AlterField(
            model_name="bookmark",
            name="last_check",
            field=models.DateTimeField(
                help_text="Timestamp of the last URL availability check", null=True
            ),
        ),
        migrations.AlterField(
            model_name="bookmark",
            name="last_response_code",
            field=models.IntegerField(
                help_text="HTTP status code from the last availability check", null=True
            ),
        ),
    ]
