# Generated by Django 5.2.8 on 2025-11-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_userprofile_google_calendar_email"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="usernote",
            unique_together=set(),
        ),
        migrations.RenameField(
            model_name="usernote",
            old_name="note",
            new_name="blob",
        ),
        migrations.AddField(
            model_name="usernote",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="usernote",
            unique_together={("userprofile", "blob")},
        ),
    ]
