# Generated by Django 5.2.8 on 2025-11-22 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_alter_usernote_unique_together_usernote_blob_and_more"),
        ("blob", "0031_alter_blob_bc_objects"),
        ("feed", "0005_feed_verify_ssl_certificate"),
        ("tag", "0018_tag_check_name_is_lowercase"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="drilltag",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="userfeed",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="usernote",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="usertag",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="drilltag",
            constraint=models.UniqueConstraint(
                fields=("userprofile", "tag"),
                name="accounts_drilltag_userprofile_tag_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="userfeed",
            constraint=models.UniqueConstraint(
                fields=("userprofile", "feed"),
                name="accounts_userfeed_userprofile_feed_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="usernote",
            constraint=models.UniqueConstraint(
                fields=("userprofile", "blob"),
                name="accounts_usernote_userprofile_blob_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="usertag",
            constraint=models.UniqueConstraint(
                fields=("userprofile", "tag"),
                name="accounts_usertag_userprofile_tag_uniq",
            ),
        ),
    ]
