# Generated by Django 5.2.8 on 2025-11-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_alter_drilltag_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="weather",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
