# Generated by Django 5.2.8 on 2025-11-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_userprofile_weather"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="nytimes_api_key",
            field=models.TextField(blank=True, null=True),
        ),
    ]
