# Generated by Django 5.2.8 on 2026-01-12 20:31

import accounts.themes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_alter_userprofile_nytimes_api_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="theme",
            field=models.CharField(
                choices=accounts.themes.get_theme_choices,
                default="light",
                max_length=20,
            ),
        ),
    ]
