# Generated by Django 5.2.13 on 2026-04-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_alter_userprofile_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="sidebar_order",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
