# Generated by Django 5.2.13 on 2026-04-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0024_userprofile_sidebar_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="bookmarks_per_page",
            field=models.PositiveIntegerField(default=50),
        ),
    ]
