# Generated by Django 5.2.14 on 2026-05-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0026_usersession"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="topbar_animation",
            field=models.CharField(
                choices=[
                    ("aurora", "Aurora"),
                    ("constellations", "Constellations"),
                    ("none", "None"),
                ],
                default="aurora",
                max_length=32,
            ),
        ),
    ]
