# Generated by Django 5.2.14 on 2026-05-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0027_userprofile_topbar_animation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="topbar_animation",
            field=models.CharField(
                choices=[
                    ("aurora", "Aurora"),
                    ("constellations", "Constellations"),
                    ("fireflies", "Fireflies"),
                    ("none", "None"),
                ],
                default="aurora",
                max_length=32,
            ),
        ),
    ]
