# Generated by Django 5.2.14 on 2026-05-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0028_alter_userprofile_topbar_animation"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="visualizer",
            field=models.CharField(
                choices=[
                    ("torus", "Torus"),
                    ("icosahedron", "Icosahedron"),
                    ("tesseract", "Tesseract"),
                    ("mobius", "Möbius strip"),
                    ("globe", "Globe"),
                    ("random", "Random"),
                    ("none", "None"),
                ],
                default="torus",
                max_length=32,
            ),
        ),
    ]
