# Generated by Django 5.2.14 on 2026-06-07 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0030_alter_userprofile_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="weather_location",
            field=models.CharField(blank=True, default="02138", max_length=100),
        ),
    ]
