# Generated by Django 5.2.11 on 2026-03-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0003_convert_null_textfields_to_empty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="asin",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="book",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="book",
            name="publisher",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="book",
            name="subtitle",
            field=models.TextField(blank=True, default=""),
        ),
    ]
