# Generated by Django 5.2.14 on 2026-06-08 00:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0004_alter_book_asin_alter_book_isbn_alter_book_notes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="asin",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="book",
            name="year",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(2100),
                ],
            ),
        ),
    ]
