"""
URL configuration for the Blob app.
"""

from django.urls import path

from . import views

app_name = "blob"

urlpatterns = [
    path(
        route="list",
        view=views.BlobListView.as_view(),
        name="list"
    ),
    path(
        route="<uuid:uuid>/",
        view=views.BlobDetailView.as_view(),
        name="detail"
    ),
    path(
        route="<uuid:uuid>/update/",
        view=views.BlobUpdateView.as_view(),
        name="update"
    ),
    path(
        route="create/",
        view=views.BlobCreateView.as_view(),
        name="create"
    ),
    path(
        route="metadata_name_search/",
        view=views.metadata_name_search,
        name="metadata_name_search"
    ),
    path(
        route="parse_date/<path:input_date>/",
        view=views.parse_date,
        name="parse_date"
    ),
    path(
        route="update_cover_image",
        view=views.update_cover_image,
        name="update_cover_image"
    ),
    path(
        route="elasticsearch_info/<uuid:uuid>",
        view=views.get_elasticsearch_info,
        name="get_elasticsearch_info"
    ),
    path(
        route="clone/<uuid:uuid>",
        view=views.BlobCloneView.as_view(),
        name="clone"
    ),
    path(
        route="import",
        view=views.BlobImportView.as_view(),
        name="import"
    ),
    path(
        route="related_objects/<uuid:uuid>",
        view=views.get_related_objects,
        name="related_objects"
    ),
    path(
        route="related_objects/add",
        view=views.add_related_object,
        name="add_related_object"
    ),
    path(
        route="related_objects/remove",
        view=views.remove_related_object,
        name="remove_related_object"
    ),
    path(
        route="update_page_number",
        view=views.update_page_number,
        name="update_page_number"
    ),
    path(
        route="related_objects/sort",
        view=views.sort_related_objects,
        name="sort_related_objects"
    ),
    path(
        route="related_objects/note/update",
        view=views.update_related_object_note,
        name="update_related_object_note"
    ),
    path(
        route="<uuid:uuid>/file/",
        view=views.blob_file_serve,
        name="file"
    ),
    path(
        route="template",
        view=views.get_template,
        name="get_template"
    ),
    path(
        route="chat",
        view=views.chat,
        name="chat"
    ),
    path(
        route="bookshelf",
        view=views.BookshelfListView.as_view(),
        name="bookshelf"
    ),
]
