# Generated by Django 5.2.8 on 2025-11-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blob", "0031_alter_blob_bc_objects"),
        ("bookmark", "0010_bookmark_data"),
        ("drill", "0029_alter_question_bc_objects"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="questiontoobject",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="questiontoobject",
            constraint=models.UniqueConstraint(
                fields=("node", "blob"), name="uniq_node_blob"
            ),
        ),
        migrations.AddConstraint(
            model_name="questiontoobject",
            constraint=models.UniqueConstraint(
                fields=("node", "bookmark"), name="uniq_node_bookmark"
            ),
        ),
        migrations.AddConstraint(
            model_name="questiontoobject",
            constraint=models.UniqueConstraint(
                fields=("node", "question"), name="uniq_node_question"
            ),
        ),
    ]
