# Generated by Django 5.2.11 on 2026-03-08 15:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drill", "0030_alter_questiontoobject_unique_together_and_more"),
        ("tag", "0020_replace_unique_together_with_constraints"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={},
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["user", "last_reviewed"], name="drill_quest_user_id_f78264_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["user", "is_disabled"], name="drill_quest_user_id_db92fa_idx"
            ),
        ),
    ]
