# Generated by Django 5.2.11 on 2026-03-08 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drill", "0031_alter_question_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="interval",
            field=models.DurationField(
                default=datetime.timedelta(days=1),
                help_text="Current spaced-repetition interval between reviews",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="interval_index",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Position in the user's drill_intervals schedule list",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="is_disabled",
            field=models.BooleanField(
                default=False,
                help_text="Disabled questions are excluded from study sessions",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="is_reversible",
            field=models.BooleanField(
                default=False,
                help_text="If true, question and answer can be swapped during review",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="times_failed",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of times the user answered incorrectly"
            ),
        ),
    ]
