# Generated by Django 5.2.14 on 2026-05-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drill", "0032_alter_question_interval_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="allow_data_variation",
            field=models.BooleanField(
                default=False,
                help_text="If true, the rephrase feature may also vary numbers/names in the question and generate a matching new answer. If false, rephrasing only reworks phrasing and the stored answer remains valid.",
            ),
        ),
    ]
