# Generated by Django 5.2.14 on 2026-05-23 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drill", "0033_add_allow_data_variation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="allow_data_variation",
        ),
    ]
