# Generated by Django 5.2.11 on 2026-03-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reminder", "0003_add_schedule_type_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reminder",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="reminder",
            name="next_trigger_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
