# Generated by Django 5.2.11 on 2026-03-08 17:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reminder", "0004_name_charfield_next_trigger_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reminder",
            options={},
        ),
        migrations.AddConstraint(
            model_name="reminder",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="unique_reminder_user_name"
            ),
        ),
    ]
