# Generated by Django 5.2.11 on 2026-03-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reminder", "0005_alter_reminder_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reminder",
            name="create_todo",
            field=models.BooleanField(
                default=False,
                help_text="Auto-create a Todo task when this reminder triggers",
            ),
        ),
        migrations.AlterField(
            model_name="reminder",
            name="days_of_month",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Day-of-month numbers (1-31) for monthly reminders",
            ),
        ),
        migrations.AlterField(
            model_name="reminder",
            name="days_of_week",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Weekday indices for weekly reminders (0=Mon, 6=Sun)",
            ),
        ),
        migrations.AlterField(
            model_name="reminder",
            name="interval_unit",
            field=models.CharField(
                choices=[
                    ("hour", "Hour"),
                    ("day", "Day"),
                    ("week", "Week"),
                    ("month", "Month"),
                ],
                default="day",
                help_text="Deprecated: legacy interval time unit",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="reminder",
            name="interval_value",
            field=models.PositiveSmallIntegerField(
                default=1, help_text="Deprecated: legacy interval numeric value"
            ),
        ),
        migrations.AlterField(
            model_name="reminder",
            name="schedule_type",
            field=models.CharField(
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                ],
                default="daily",
                help_text="How often the reminder repeats: daily, weekly, or monthly",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="reminder",
            name="start_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the schedule begins; defaults to creation time",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="reminder",
            name="trigger_time",
            field=models.TimeField(
                blank=True, help_text="Time of day when the reminder fires", null=True
            ),
        ),
    ]
