# Generated by Django 5.2.16 on 2026-08-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reminder", "0006_alter_reminder_create_todo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reminder",
            name="months",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Month numbers (1-12) for yearly reminders; each fires on the 1st of the month",
            ),
        ),
        migrations.AlterField(
            model_name="reminder",
            name="schedule_type",
            field=models.CharField(
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                    ("yearly", "Yearly"),
                ],
                default="daily",
                help_text="How often the reminder repeats: daily, weekly, monthly, or yearly",
                max_length=10,
            ),
        ),
    ]
