# Generated by Django 5.2.8 on 2025-11-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blob", "0031_alter_blob_bc_objects"),
        ("bookmark", "0010_bookmark_data"),
        ("collection", "0025_rename_is_private_collection_is_favorite"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="collectionobject",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="collectionobject",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("blob__isnull", False), ("bookmark__isnull", True)),
                    models.Q(("blob__isnull", True), ("bookmark__isnull", False)),
                    _connector="OR",
                ),
                name="collection_object_has_exactly_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionobject",
            constraint=models.UniqueConstraint(
                condition=models.Q(("blob__isnull", False)),
                fields=("collection", "blob"),
                name="unique_collection_blob",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionobject",
            constraint=models.UniqueConstraint(
                condition=models.Q(("bookmark__isnull", False)),
                fields=("collection", "bookmark"),
                name="unique_collection_bookmark",
            ),
        ),
    ]
