# Generated by Django 5.2.11 on 2026-03-03 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0026_alter_collectionobject_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collectionobject",
            name="object",
        ),
        migrations.RemoveField(
            model_name="collection",
            name="bc_objects",
        ),
        migrations.DeleteModel(
            name="BCObject",
        ),
    ]
