# Generated by Django 5.2.11 on 2026-03-08 15:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0027_remove_bcobject_and_related_fields"),
        ("tag", "0020_replace_unique_together_with_constraints"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collection",
            options={},
        ),
        migrations.AddIndex(
            model_name="collection",
            index=models.Index(
                fields=["user", "-created"], name="collection__user_id_31ed14_idx"
            ),
        ),
    ]
