# Generated by Django 5.2.11 on 2026-03-08 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0028_alter_collection_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collection",
            options={"ordering": ("-modified", "-created")},
        ),
    ]
