# Generated by Django 5.2.14 on 2026-06-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0029_alter_collection_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="collectionobject",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
