# Generated by Django 5.2.8 on 2025-11-25 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0005_metric_frequency"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="metricdata",
            options={"ordering": ["-created"]},
        ),
        migrations.AlterField(
            model_name="metricdata",
            name="metric",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data_points",
                to="metrics.metric",
            ),
        ),
    ]
