# Generated by Django 5.2.11 on 2026-03-08 17:32

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0006_alter_metricdata_options_alter_metricdata_metric"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metric",
            name="frequency",
            field=models.DurationField(
                default=datetime.timedelta(days=1),
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.timedelta(seconds=60)
                    )
                ],
            ),
        ),
    ]
