# Generated by Django 5.2.11 on 2026-03-08 18:19

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0007_alter_metric_frequency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metric",
            name="frequency",
            field=models.DurationField(
                default=datetime.timedelta(days=1),
                help_text="How often this metric should be updated (e.g. 1 day)",
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.timedelta(seconds=60)
                    )
                ],
            ),
        ),
    ]
