# Generated by Django 5.2.14 on 2026-06-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0008_alter_metric_frequency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metric",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="metricdata",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
