[program:daphne]
command = /var/www/django/bordercore/bin/daphne_start
user = www-data
autostart = true
autorestart = true
redirect_stderr = true
stdout_logfile = /var/log/django/daphne_supervisor.log
stopsignal = INT
