import React from "react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faPencilAlt, faInfo, faTimes } from "@fortawesome/free-solid-svg-icons";
import axios from "axios";
import MarkdownIt from "markdown-it";
import type { Song, Album, AlbumDetailUrls, Playlist } from "./types";
import SongTable from "./SongTable";
import AudioPlayer, { type AudioPlayerHandle } from "./AudioPlayer";
import EditAlbumModal, { type EditAlbumModalHandle } from "./EditAlbumModal";
import DropDownMenu from "../common/DropDownMenu";
import { EventBus } from "../utils/reactUtils";

// markdown-it for rendering album notes
// Note: Content is user-generated by authenticated users and stored in the database.
// markdown-it provides built-in HTML sanitization for safe rendering.
const markdown = new MarkdownIt({
  html: true,
  linkify: true,
  typographer: true,
});

interface AlbumDetailPageProps {
  album: Album;
  songs: Song[];
  initialTags: string[];
  playlists: Playlist[];
  urls: AlbumDetailUrls;
  staticUrl: string;
  csrfToken: string;
  defaultPlaylist: string;
}

export function AlbumDetailPage({
  album,
  songs: initialSongs,
  initialTags,
  playlists,
  urls,
  staticUrl,
  csrfToken,
  defaultPlaylist,
}: AlbumDetailPageProps) {
  const [songs, setSongs] = React.useState<Song[]>(initialSongs);
  const [currentSongUuid, setCurrentSongUuid] = React.useState<string | null>(null);
  const [isPlaying, setIsPlaying] = React.useState(false);

  const audioPlayerRef = React.useRef<AudioPlayerHandle>(null);
  const editAlbumRef = React.useRef<EditAlbumModalHandle>(null);

  const handleCurrentSong = (songIndex: number) => {
    if (songIndex === -1) {
      setCurrentSongUuid(null);
    } else if (songs[songIndex]) {
      setCurrentSongUuid(songs[songIndex].uuid);
    }
  };

  const handleIsPlaying = (playing: boolean) => {
    setIsPlaying(playing);
  };

  const handleSongClick = (song: Song) => {
    audioPlayerRef.current?.playTrack(song.uuid);
    setCurrentSongUuid(song.uuid);
  };

  const handleRatingChange = (songUuid: string, newRating: number | null) => {
    setSongs(prevSongs =>
      prevSongs.map(song => (song.uuid === songUuid ? { ...song, rating: newRating } : song))
    );
  };

  const handlePlaylistToggle = (
    songUuid: string,
    playlistUuid: string,
    action: "added" | "removed"
  ) => {
    setSongs(prevSongs =>
      prevSongs.map(song => {
        if (song.uuid !== songUuid) return song;
        if (action === "added") {
          return { ...song, playlists: [...song.playlists, playlistUuid] };
        } else {
          return { ...song, playlists: song.playlists.filter(p => p !== playlistUuid) };
        }
      })
    );
  };

  const handleEditAlbum = () => {
    editAlbumRef.current?.openModal();
  };

  const handleAlbumInfo = () => {
    EventBus.$emit("chat", {
      content: `Tell me about the album ${album.title} by the band or artist ${album.artist_name}`,
    });
  };

  const handleDeleteAlbum = async () => {
    if (!confirm("Are you sure you want to delete this album?")) {
      return;
    }

    try {
      await axios.delete(urls.deleteAlbum, {
        headers: {
          "X-CSRFToken": csrfToken,
        },
        withCredentials: true,
      });
      window.location.href = urls.musicList;
    } catch (error) {
      console.error("Error deleting album:", error);
    }
  };

  // Render album note with markdown - content is sanitized by markdown-it
  const renderAlbumNote = () => {
    if (!album.note) return null;
    return { __html: markdown.render(album.note) };
  };

  return (
    <div className="row g-0 h-100 align-items-start">
      {/* Sidebar - Album artwork and player */}
      <div className="sticky-top col-lg-3 d-flex flex-column">
        <div className="card-grid ms-4 d-flex flex-column align-items-center">
          <img
            src={album.cover_url}
            className="mw-100"
            height={400}
            width={400}
            alt={`${album.title} cover`}
          />

          {album.note && <h5 className="mt-3" dangerouslySetInnerHTML={renderAlbumNote()!} />}

          <AudioPlayer
            ref={audioPlayerRef}
            trackList={songs}
            songUrl={urls.songMedia}
            markListenedToUrl={urls.markListenedTo}
            csrfToken={csrfToken}
            onCurrentSong={handleCurrentSong}
            onIsPlaying={handleIsPlaying}
          />

          {album.tags.length > 0 && (
            <div className="align-self-start ms-3 mt-3 mb-3">
              Tags:{" "}
              {album.tags.map((tag, index) => (
                <span key={index} className="tag">
                  {tag}
                </span>
              ))}
            </div>
          )}
        </div>
      </div>

      {/* Main content - Album info and song table */}
      <div className="col-lg-9 h-100 me-0">
        <div className="card-grid h-100 ms-4">
          <div className="d-flex flex-column h-100 me-2">
            {/* Album header card */}
            <div className="card backdrop-filter hover-target me-0">
              <div className="card-body">
                <div className="d-flex">
                  <h1>{album.title}</h1>
                  <div className="ms-auto">
                    <DropDownMenu
                      showOnHover={false}
                      dropdownSlot={
                        <ul className="dropdown-menu-list">
                          <li>
                            <button className="dropdown-menu-item" onClick={handleEditAlbum}>
                              <span className="dropdown-menu-icon">
                                <FontAwesomeIcon icon={faPencilAlt} />
                              </span>
                              <span className="dropdown-menu-text">Edit</span>
                            </button>
                          </li>
                          <li>
                            <button className="dropdown-menu-item" onClick={handleAlbumInfo}>
                              <span className="dropdown-menu-icon">
                                <FontAwesomeIcon icon={faInfo} />
                              </span>
                              <span className="dropdown-menu-text">Album Info</span>
                            </button>
                          </li>
                          {!album.has_songs && (
                            <li>
                              <button className="dropdown-menu-item" onClick={handleDeleteAlbum}>
                                <span className="dropdown-menu-icon">
                                  <FontAwesomeIcon icon={faTimes} />
                                </span>
                                <span className="dropdown-menu-text">Delete Album</span>
                              </button>
                            </li>
                          )}
                        </ul>
                      }
                    />
                  </div>
                </div>
                <h3>
                  <a href={urls.artistDetail}>{album.artist_name}</a>
                </h3>
                <h6>{album.year}</h6>
                {album.original_release_year && album.original_release_year !== album.year && (
                  <h5>Originally released {album.original_release_year}</h5>
                )}
                <h6 className="text-primary smaller">
                  <small>{album.playtime}</small>
                </h6>
              </div>
            </div>

            {/* Song table */}
            <div className="flex-grow-1 me-0 mt-3 mb-3" id="album-song-list">
              <SongTable
                songs={songs}
                currentSongUuid={currentSongUuid}
                isPlaying={isPlaying}
                staticUrl={staticUrl}
                setSongRatingUrl={urls.setSongRating}
                editSongUrlTemplate={urls.editSong}
                addToPlaylistUrl={urls.addToPlaylist}
                csrfToken={csrfToken}
                playlists={playlists}
                onSongClick={handleSongClick}
                onRatingChange={handleRatingChange}
                onPlaylistToggle={handlePlaylistToggle}
              />
            </div>
          </div>
        </div>
      </div>

      {/* Modals */}
      <EditAlbumModal
        ref={editAlbumRef}
        album={album}
        initialTags={initialTags}
        updateAlbumUrl={urls.updateAlbum}
        searchArtistsUrl={urls.searchArtists}
        searchTagsUrl={urls.searchTags}
        csrfToken={csrfToken}
      />
    </div>
  );
}

export default AlbumDetailPage;
