import React from "react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faPencilAlt, faInfo, faTimes } from "@fortawesome/free-solid-svg-icons";
import axios from "axios";
import MarkdownIt from "markdown-it";
import type { Song, Album, AlbumDetailUrls, Playlist } from "./types";
import SongTable from "./AlbumSongTable";
import EditAlbumModal, { type EditAlbumModalHandle } from "./EditAlbumModal";
import DropDownMenu from "../common/DropDownMenu";
import { doDelete, EventBus } from "../utils/reactUtils";
import { tagStyle } from "../utils/tagColors";

// markdown-it for rendering album notes
// Note: Content is user-generated by authenticated users and stored in the database.
// markdown-it provides built-in HTML sanitization for safe rendering.
const markdown = new MarkdownIt({
  html: true,
  linkify: true,
  typographer: true,
});

interface AlbumDetailPageProps {
  album: Album;
  songs: Song[];
  initialTags: string[];
  playlists: Playlist[];
  urls: AlbumDetailUrls;
  staticUrl: string;
  defaultPlaylist: string;
}

export function AlbumDetailPage({
  album,
  songs: initialSongs,
  initialTags,
  playlists,
  urls,
  staticUrl,
  defaultPlaylist,
}: AlbumDetailPageProps) {
  const [songs, setSongs] = React.useState<Song[]>(initialSongs);
  const [currentSongUuid, setCurrentSongUuid] = React.useState<string | null>(null);
  const [isPlaying, setIsPlaying] = React.useState(false);

  const editAlbumRef = React.useRef<EditAlbumModalHandle>(null);

  const handleCurrentSong = (songIndex: number) => {
    if (songIndex === -1) {
      setCurrentSongUuid(null);
    } else if (songs[songIndex]) {
      setCurrentSongUuid(songs[songIndex].uuid);
    }
  };

  const handleIsPlaying = (playing: boolean) => {
    setIsPlaying(playing);
  };

  React.useEffect(() => {
    const onPlay = (data: { uuid: string }) => {
      setIsPlaying(true);
      setCurrentSongUuid(data.uuid);
    };
    const onPause = () => {
      setIsPlaying(false);
    };
    const onEnded = () => {
      setIsPlaying(false);
      setCurrentSongUuid(null);
    };

    EventBus.$on("audio-play", onPlay);
    EventBus.$on("audio-pause", onPause);
    EventBus.$on("audio-ended", onEnded);

    return () => {
      EventBus.$off("audio-play", onPlay);
      EventBus.$off("audio-pause", onPause);
      EventBus.$off("audio-ended", onEnded);
    };
  }, []);

  const handleSongClick = (song: Song) => {
    const enriched = songs.map(s => ({ ...s, artist: album.artist_name }));
    EventBus.$emit("play-track", {
      track: { ...song, artist: album.artist_name },
      trackList: enriched,
      songUrl: urls.songMedia,
      markListenedToUrl: urls.markListenedTo,
    });
    setCurrentSongUuid(song.uuid);
  };

  const handleRatingChange = (songUuid: string, newRating: number | null) => {
    setSongs(prevSongs =>
      prevSongs.map(song => (song.uuid === songUuid ? { ...song, rating: newRating } : song))
    );
  };

  const handlePlaylistToggle = (
    songUuid: string,
    playlistUuid: string,
    action: "added" | "removed"
  ) => {
    setSongs(prevSongs =>
      prevSongs.map(song => {
        if (song.uuid !== songUuid) return song;
        if (action === "added") {
          return { ...song, playlists: [...song.playlists, playlistUuid] };
        } else {
          return { ...song, playlists: song.playlists.filter(p => p !== playlistUuid) };
        }
      })
    );
  };

  const handleEditAlbum = () => {
    editAlbumRef.current?.openModal();
  };

  const handleAlbumInfo = () => {
    EventBus.$emit("chat", {
      content: `Tell me about the album ${album.title} by the band or artist ${album.artist_name}`,
    });
  };

  const handleDeleteAlbum = () => {
    if (!confirm("Are you sure you want to delete this album?")) {
      return;
    }

    doDelete(
      urls.deleteAlbum,
      () => {
        window.location.href = urls.musicList;
      },
      "Album successfully deleted"
    );
  };

  // Render album note with markdown - content is sanitized by markdown-it
  const renderAlbumNote = () => {
    if (!album.note) return null;
    return { __html: markdown.render(album.note) };
  };

  return (
    <div className="row g-0 h-full items-start">
      {/* Sidebar - Album artwork and player */}
      <div className="sticky-top col-lg-3 flex flex-col">
        <div className="card-grid ms-6 flex flex-col items-center">
          <img
            src={album.cover_url}
            className="max-w-full"
            height={400}
            width={400}
            alt={`${album.title} cover`}
          />

          {album.note && <h5 className="mt-4" dangerouslySetInnerHTML={renderAlbumNote()!} />}

          {album.tags.length > 0 && (
            <div className="align-self-start ms-4 mt-4 mb-4">
              Tags:{" "}
              {album.tags.map((tag, index) => (
                <span
                  key={index}
                  className="tag"
                  style={tagStyle(tag)} // must remain inline
                >
                  {tag}
                </span>
              ))}
            </div>
          )}
        </div>
      </div>

      {/* Main content - Album info and song table */}
      <div className="col-lg-9 h-full me-0">
        <div className="card-grid h-full ms-6">
          <div className="flex flex-col h-full me-2">
            {/* Album header card */}
            <div className="card backdrop-filter hover-target me-0">
              <div className="card-body">
                <div className="flex">
                  <h1>{album.title}</h1>
                  <div className="ms-auto">
                    <DropDownMenu
                      dropdownSlot={
                        <ul className="dropdown-menu-list">
                          <li>
                            <button className="dropdown-menu-item" onClick={handleEditAlbum}>
                              <span className="dropdown-menu-icon">
                                <FontAwesomeIcon icon={faPencilAlt} />
                              </span>
                              <span className="dropdown-menu-text">Edit</span>
                            </button>
                          </li>
                          <li>
                            <button className="dropdown-menu-item" onClick={handleAlbumInfo}>
                              <span className="dropdown-menu-icon">
                                <FontAwesomeIcon icon={faInfo} />
                              </span>
                              <span className="dropdown-menu-text">Album Info</span>
                            </button>
                          </li>
                          {!album.has_songs && (
                            <li>
                              <button className="dropdown-menu-item" onClick={handleDeleteAlbum}>
                                <span className="dropdown-menu-icon">
                                  <FontAwesomeIcon icon={faTimes} />
                                </span>
                                <span className="dropdown-menu-text">Delete Album</span>
                              </button>
                            </li>
                          )}
                        </ul>
                      }
                    />
                  </div>
                </div>
                <h3>
                  <a href={urls.artistDetail}>{album.artist_name}</a>
                </h3>
                <h6>{album.year}</h6>
                {album.original_release_year && album.original_release_year !== album.year && (
                  <h5>Originally released {album.original_release_year}</h5>
                )}
                <h6 className="text-primary smaller">
                  <small>{album.playtime}</small>
                </h6>
              </div>
            </div>

            {/* Song table */}
            <div className="grow me-0 mt-4 mb-4" id="album-song-list">
              <SongTable
                songs={songs}
                currentSongUuid={currentSongUuid}
                isPlaying={isPlaying}
                staticUrl={staticUrl}
                setSongRatingUrl={urls.setSongRating}
                editSongUrlTemplate={urls.editSong}
                addToPlaylistUrl={urls.addToPlaylist}
                playlists={playlists}
                onSongClick={handleSongClick}
                onRatingChange={handleRatingChange}
                onPlaylistToggle={handlePlaylistToggle}
              />
            </div>
          </div>
        </div>
      </div>

      {/* Modals */}
      <EditAlbumModal
        ref={editAlbumRef}
        album={album}
        initialTags={initialTags}
        updateAlbumUrl={urls.updateAlbum}
        searchArtistsUrl={urls.searchArtists}
        searchTagsUrl={urls.searchTags}
      />
    </div>
  );
}

export default AlbumDetailPage;
