import React from "react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faPencilAlt,
  faInfo,
  faTimes,
  faPlay,
  faShuffle,
  faPlus,
  faCheck,
} from "@fortawesome/free-solid-svg-icons";
import axios from "axios";
import { createMarkdown } from "../common/markdown";
import type { Song, Album, AlbumDetailUrls, Playlist } from "./types";
import AlbumTrackList from "./AlbumTrackList";
import EditAlbumModal, { type EditAlbumModalHandle } from "./EditAlbumModal";
import DropDownMenu from "../common/DropDownMenu";
import ImageLightbox from "../common/ImageLightbox";
import { doDelete, EventBus } from "../utils/reactUtils";
import { tagStyle } from "../utils/tagColors";

// markdown-it for rendering album notes
// Note: Content is user-generated by authenticated users and stored in the database.
// markdown-it provides built-in HTML sanitization for safe rendering.
const markdown = createMarkdown({
  html: true,
  linkify: true,
  typographer: true,
});

interface AlbumDetailPageProps {
  album: Album;
  songs: Song[];
  initialTags: string[];
  playlists: Playlist[];
  urls: AlbumDetailUrls;
  staticUrl: string;
  defaultPlaylist: string;
}

export function AlbumDetailPage({
  album,
  songs: initialSongs,
  initialTags,
  playlists,
  urls,
  staticUrl: _staticUrl,
  defaultPlaylist: _defaultPlaylist,
}: AlbumDetailPageProps) {
  const [songs, setSongs] = React.useState<Song[]>(initialSongs);
  const [currentSongUuid, setCurrentSongUuid] = React.useState<string | null>(null);
  const [isPlaying, setIsPlaying] = React.useState(false);
  const [isCoverLightboxOpen, setIsCoverLightboxOpen] = React.useState(false);

  const editAlbumRef = React.useRef<EditAlbumModalHandle>(null);

  React.useEffect(() => {
    const onPlay = (data: { uuid: string }) => {
      setIsPlaying(true);
      setCurrentSongUuid(data.uuid);
    };
    const onPause = () => {
      setIsPlaying(false);
    };
    const onEnded = () => {
      setIsPlaying(false);
      setCurrentSongUuid(null);
    };

    EventBus.$on("audio-play", onPlay);
    EventBus.$on("audio-pause", onPause);
    EventBus.$on("audio-ended", onEnded);

    return () => {
      EventBus.$off("audio-play", onPlay);
      EventBus.$off("audio-pause", onPause);
      EventBus.$off("audio-ended", onEnded);
    };
  }, []);

  const handleSongClick = (song: Song, autoPlayNext?: boolean) => {
    const enriched = songs.map(s => ({ ...s, artist: album.artist_name }));
    EventBus.$emit("play-track", {
      track: { ...song, artist: album.artist_name },
      trackList: enriched,
      songUrl: urls.songMedia,
      markListenedToUrl: urls.markListenedTo,
      autoPlayNext,
    });
    setCurrentSongUuid(song.uuid);
  };

  const handlePlayAlbum = () => {
    if (songs.length > 0) {
      handleSongClick(songs[0], true);
    }
  };

  const handleShuffle = () => {
    if (songs.length > 0) {
      handleSongClick(songs[Math.floor(Math.random() * songs.length)]);
    }
  };

  const handleRatingChange = (songUuid: string, newRating: number | null) => {
    setSongs(prevSongs =>
      prevSongs.map(song => (song.uuid === songUuid ? { ...song, rating: newRating } : song))
    );
  };

  const handlePlaylistToggle = (
    songUuid: string,
    playlistUuid: string,
    action: "added" | "removed"
  ) => {
    setSongs(prevSongs =>
      prevSongs.map(song => {
        if (song.uuid !== songUuid) return song;
        if (action === "added") {
          return { ...song, playlists: [...song.playlists, playlistUuid] };
        } else {
          return { ...song, playlists: song.playlists.filter(p => p !== playlistUuid) };
        }
      })
    );
  };

  // Add every album track not already in the playlist. The endpoint toggles
  // membership, so songs already present are skipped rather than removed.
  const handleAddAlbumToPlaylist = async (playlistUuid: string) => {
    const playlistName = playlists.find(p => p.uuid === playlistUuid)?.name || "playlist";
    const songsToAdd = songs.filter(song => !song.playlists.includes(playlistUuid));

    if (songsToAdd.length === 0) {
      EventBus.$emit("toast", {
        body: `All tracks are already in ${playlistName}`,
        variant: "success",
      });
      return;
    }

    let addedCount = 0;
    try {
      for (const song of songsToAdd) {
        const params = new URLSearchParams();
        params.append("playlist_uuid", playlistUuid);
        params.append("song_uuid", song.uuid);

        const response = await axios.post(urls.addToPlaylist, params, {
          headers: {
            "Content-Type": "application/x-www-form-urlencoded",
          },
          withCredentials: true,
        });
        handlePlaylistToggle(song.uuid, playlistUuid, response.data.action);
        if (response.data.action === "added") {
          addedCount++;
        }
      }
      EventBus.$emit("toast", {
        body: `Added ${addedCount} ${addedCount === 1 ? "track" : "tracks"} to ${playlistName}`,
        variant: "success",
      });
    } catch (error) {
      console.error("Error adding album to playlist:", error);
      EventBus.$emit("toast", {
        body: "Failed to update playlist",
        variant: "danger",
      });
    }
  };

  const handleEditAlbum = () => {
    editAlbumRef.current?.openModal();
  };

  const handleAlbumInfo = () => {
    EventBus.$emit("chat", {
      content: `Tell me about the album ${album.title} by the band or artist ${album.artist_name}`,
    });
  };

  const handleDeleteAlbum = () => {
    if (!confirm("Are you sure you want to delete this album?")) {
      return;
    }

    doDelete(
      urls.deleteAlbum,
      () => {
        window.location.href = urls.musicList;
      },
      "Album successfully deleted"
    );
  };

  // Render album note with markdown - content is sanitized by markdown-it
  const renderAlbumNote = () => {
    if (!album.note) return null;
    return { __html: markdown.render(album.note) };
  };

  const ratedSongs = songs.filter(song => (song.rating ?? 0) > 0);
  const ratedCount = ratedSongs.length;
  const averageRating =
    ratedCount > 0 ? ratedSongs.reduce((sum, song) => sum + (song.rating ?? 0), 0) / ratedCount : 0;
  const filledStars = Math.round(averageRating);

  return (
    <div className="adp-page">
      {/* Hero: blurred art wash + scrim + content */}
      <section className="adp-hero">
        {album.cover_url && (
          <img src={album.cover_url} alt="" aria-hidden="true" className="adp-hero-art" />
        )}
        <div className="adp-hero-scrim" />
        <div className="adp-hero-content">
          {album.cover_url ? (
            <button
              type="button"
              className="adp-cover-button"
              onClick={() => setIsCoverLightboxOpen(true)}
              aria-label="View cover art fullscreen"
            >
              <img src={album.cover_url} className="adp-cover" alt={`${album.title} cover`} />
            </button>
          ) : (
            <div className="adp-cover adp-cover-placeholder" />
          )}
          <div className="adp-hero-text">
            <span className="adp-eyebrow">album · in your library</span>
            <div>
              <h1 className="adp-title">{album.title}</h1>
              <a className="adp-artist" href={urls.artistDetail}>
                {album.artist_name}
              </a>
            </div>
            <div className="adp-meta">
              {album.year && <span>{album.year}</span>}
              {album.year && <span className="adp-meta-sep">·</span>}
              <span>
                {songs.length} {songs.length === 1 ? "track" : "tracks"}
              </span>
              <span className="adp-meta-sep">·</span>
              <span>{album.playtime}</span>
              {ratedCount > 0 && (
                <>
                  <span className="adp-meta-sep">·</span>
                  <span className="adp-meta-stars">{"★".repeat(filledStars)}</span>
                  <span className="adp-meta-dim">
                    {averageRating.toFixed(1)} avg · {ratedCount} rated
                  </span>
                </>
              )}
              {album.original_release_year && album.original_release_year !== album.year && (
                <>
                  <span className="adp-meta-sep">·</span>
                  <span className="adp-meta-dim">
                    originally released {album.original_release_year}
                  </span>
                </>
              )}
            </div>
            <div className="adp-actions">
              <button className="adp-action-primary" onClick={handlePlayAlbum}>
                <FontAwesomeIcon icon={faPlay} />
                play album
              </button>
              <button className="adp-action-secondary" onClick={handleShuffle}>
                <FontAwesomeIcon icon={faShuffle} />
                shuffle
              </button>
              <DropDownMenu
                showTarget={false}
                iconSlot={
                  <span className="adp-action-secondary">
                    <FontAwesomeIcon icon={faPlus} />
                    playlist
                  </span>
                }
                dropdownSlot={
                  <ul className="dropdown-menu-list">
                    {playlists.map(playlist => (
                      <li key={playlist.uuid}>
                        <button
                          className="dropdown-menu-item"
                          onClick={() => handleAddAlbumToPlaylist(playlist.uuid)}
                        >
                          <span className="dropdown-menu-text">{playlist.name}</span>
                          {songs.length > 0 &&
                            songs.every(song => song.playlists.includes(playlist.uuid)) && (
                              <span className="dropdown-menu-check">
                                <FontAwesomeIcon icon={faCheck} className="text-ok" />
                              </span>
                            )}
                        </button>
                      </li>
                    ))}
                  </ul>
                }
              />
            </div>
          </div>
          <div className="adp-kebab">
            <DropDownMenu
              dropdownSlot={
                <ul className="dropdown-menu-list">
                  <li>
                    <button className="dropdown-menu-item" onClick={handleEditAlbum}>
                      <span className="dropdown-menu-icon">
                        <FontAwesomeIcon icon={faPencilAlt} />
                      </span>
                      <span className="dropdown-menu-text">Edit</span>
                    </button>
                  </li>
                  <li>
                    <button className="dropdown-menu-item" onClick={handleAlbumInfo}>
                      <span className="dropdown-menu-icon">
                        <FontAwesomeIcon icon={faInfo} />
                      </span>
                      <span className="dropdown-menu-text">Album Info</span>
                    </button>
                  </li>
                  {!album.has_songs && (
                    <li>
                      <button className="dropdown-menu-item" onClick={handleDeleteAlbum}>
                        <span className="dropdown-menu-icon">
                          <FontAwesomeIcon icon={faTimes} />
                        </span>
                        <span className="dropdown-menu-text">Delete Album</span>
                      </button>
                    </li>
                  )}
                </ul>
              }
            />
          </div>
        </div>
      </section>

      {/* Album note and tags */}
      {(album.note || album.tags.length > 0) && (
        <section className="adp-note-strip">
          {album.note && <div className="adp-note" dangerouslySetInnerHTML={renderAlbumNote()!} />}
          {album.tags.length > 0 && (
            <div className="adp-tags">
              {album.tags.map((tag, index) => (
                <span
                  key={index}
                  className="tag"
                  style={tagStyle(tag)} // must remain inline
                >
                  {tag}
                </span>
              ))}
            </div>
          )}
        </section>
      )}

      {/* Tracklist */}
      <section className="adp-tracklist-section">
        <AlbumTrackList
          songs={songs}
          currentSongUuid={currentSongUuid}
          isPlaying={isPlaying}
          setSongRatingUrl={urls.setSongRating}
          editSongUrlTemplate={urls.editSong}
          addToPlaylistUrl={urls.addToPlaylist}
          playlists={playlists}
          onSongClick={handleSongClick}
          onRatingChange={handleRatingChange}
          onPlaylistToggle={handlePlaylistToggle}
        />
      </section>

      {/* Modals */}
      {isCoverLightboxOpen && album.cover_url && (
        <ImageLightbox
          src={album.cover_url}
          alt={`${album.title} cover`}
          onClose={() => setIsCoverLightboxOpen(false)}
        />
      )}
      <EditAlbumModal
        ref={editAlbumRef}
        album={album}
        initialTags={initialTags}
        updateAlbumUrl={urls.updateAlbum}
        searchArtistsUrl={urls.searchArtists}
        searchTagsUrl={urls.searchTags}
      />
    </div>
  );
}

export default AlbumDetailPage;
