# Generated by Django 5.2.8 on 2025-11-26 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blob", "0031_alter_blob_bc_objects"),
        ("node", "0010_alter_nodetodo_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="recentlyviewedblob",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="recentlyviewedblob",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="recentlyviewedblob",
            constraint=models.UniqueConstraint(
                fields=("user", "blob"), name="uniq_recent_blob_per_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="recentlyviewedblob",
            constraint=models.UniqueConstraint(
                fields=("user", "node"), name="uniq_recent_node_per_user"
            ),
        ),
    ]
