# Generated by Django 5.2.8 on 2025-11-26 20:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blob", "0034_alter_recentlyviewedblob_user"),
        ("bookmark", "0011_alter_bookmark_note"),
        ("drill", "0030_alter_questiontoobject_unique_together_and_more"),
        ("tag", "0018_tag_check_name_is_lowercase"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="blob",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="blobtoobject",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="metadata",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="blob",
            constraint=models.UniqueConstraint(
                fields=("sha1sum", "user"), name="unique_blob_sha1sum_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="blobtoobject",
            constraint=models.UniqueConstraint(
                fields=("node", "blob"), name="unique_blobtoobject_node_blob"
            ),
        ),
        migrations.AddConstraint(
            model_name="blobtoobject",
            constraint=models.UniqueConstraint(
                fields=("node", "bookmark"), name="unique_blobtoobject_node_bookmark"
            ),
        ),
        migrations.AddConstraint(
            model_name="blobtoobject",
            constraint=models.UniqueConstraint(
                fields=("node", "question"), name="unique_blobtoobject_node_question"
            ),
        ),
        migrations.AddConstraint(
            model_name="metadata",
            constraint=models.UniqueConstraint(
                fields=("name", "value", "blob"), name="unique_metadata_name_value_blob"
            ),
        ),
    ]
