# Generated by Django 5.2.11 on 2026-03-08 15:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blob", "0035_alter_blob_unique_together_and_more"),
        ("tag", "0020_replace_unique_together_with_constraints"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="blob",
            index=models.Index(
                fields=["user", "-created"], name="blob_blob_user_id_ec3990_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="blob",
            index=models.Index(
                fields=["user", "is_note"], name="blob_blob_user_id_576684_idx"
            ),
        ),
    ]
