# Generated by Django 5.2.11 on 2026-03-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blob", "0037_convert_null_textfields_to_empty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blob",
            name="content",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="blob",
            name="date",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="blob",
            name="name",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="blob",
            name="note",
            field=models.TextField(blank=True, default=""),
        ),
    ]
