# Generated by Django 5.2.11 on 2026-03-08 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blob", "0038_alter_blob_content_alter_blob_date_alter_blob_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blob",
            options={"ordering": ("-modified", "-created")},
        ),
    ]
