# Generated by Django 5.2.11 on 2026-03-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blob", "0039_alter_blob_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blob",
            name="data",
            field=models.JSONField(
                blank=True,
                help_text="Arbitrary structured metadata (e.g. page count, dimensions)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="blob",
            name="importance",
            field=models.IntegerField(
                default=1, help_text="Search ranking boost (higher = more prominent)"
            ),
        ),
        migrations.AlterField(
            model_name="blob",
            name="is_indexed",
            field=models.BooleanField(
                default=True, help_text="Whether this blob is indexed in Elasticsearch"
            ),
        ),
        migrations.AlterField(
            model_name="blob",
            name="is_note",
            field=models.BooleanField(
                default=False,
                help_text="True if this blob is a text note rather than a file",
            ),
        ),
        migrations.AlterField(
            model_name="blob",
            name="math_support",
            field=models.BooleanField(
                default=False, help_text="Enable LaTeX/MathJax rendering for this blob"
            ),
        ),
        migrations.AlterField(
            model_name="blob",
            name="sha1sum",
            field=models.CharField(
                blank=True,
                help_text="SHA1 hash of file content, used for deduplication",
                max_length=40,
                null=True,
            ),
        ),
    ]
