# Generated by Django 5.2.13 on 2026-05-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0007_backfill_pub_date_and_dedup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feeditem",
            name="pub_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name="feeditem",
            unique_together={("feed", "link")},
        ),
    ]
