# Generated by Django 5.2.13 on 2026-05-02 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0008_pub_date_not_null_and_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="feeditem",
            name="summary",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="feeditem",
            name="thumbnail_url",
            field=models.URLField(blank=True, default="", max_length=2048),
        ),
    ]
