"""
URL configuration for the Node app.
"""

from django.urls import path

from . import views

app_name = "node"

urlpatterns = [
    path(
        route="",
        view=views.NodeListView.as_view(),
        name="list"
    ),
    path(
        route="<uuid:uuid>/",
        view=views.NodeDetailView.as_view(),
        name="detail"
    ),
    path(
        route="create/",
        view=views.NodeCreateView.as_view(),
        name="create"
    ),
    path(
        route="<uuid:uuid>/todo_list/",
        view=views.get_todo_list,
        name="get_todo_list"
    ),
    path(
        route="edit_note/",
        view=views.edit_note,
        name="edit_note"
    ),
    path(
        route="todo/add/",
        view=views.add_todo,
        name="add_todo"
    ),
    path(
        route="todo/remove/",
        view=views.remove_todo,
        name="remove_todo"
    ),
    path(
        route="todo/sort/",
        view=views.sort_todos,
        name="sort_todos"
    ),
    path(
        route="change_layout",
        view=views.change_layout,
        name="change_layout"
    ),
    path(
        route="collection/add",
        view=views.add_collection,
        name="add_collection"
    ),
    path(
        route="collection/update/",
        view=views.update_collection,
        name="update_collection"
    ),
    path(
        route="collection/delete",
        view=views.delete_collection,
        name="delete_collection"
    ),
    path(
        route="note/add",
        view=views.add_note,
        name="add_note"
    ),
    path(
        route="note/delete",
        view=views.delete_note,
        name="delete_note"
    ),
    path(
        route="note/color",
        view=views.set_note_color,
        name="set_note_color"
    ),
    path(
        route="image/add",
        view=views.add_image,
        name="add_image"
    ),
    path(
        route="quote/add/",
        view=views.add_quote,
        name="add_quote"
    ),
    path(
        route="quote/update/",
        view=views.update_quote,
        name="update_quote"
    ),
    path(
        route="quote/get/",
        view=views.get_quote,
        name="get_quote"
    ),
    path(
        route="todo_list/add/",
        view=views.add_todo_list,
        name="add_todo_list"
    ),
    path(
        route="todo_list/delete/",
        view=views.delete_todo_list,
        name="delete_todo_list"
    ),
    path(
        route="node/add",
        view=views.add_node,
        name="add_node"
    ),
    path(
        route="node/update/",
        view=views.update_node,
        name="update_node"
    ),
    path(
        route="node/search",
        view=views.search,
        name="search"
    ),
    path(
        route="<uuid:uuid>/preview/",
        view=views.node_preview,
        name="preview"
    ),
    path(
        route="component/remove",
        view=views.remove_component,
        name="remove_component"
    ),
]
