# Generated by Django 5.2.8 on 2025-11-25 18:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0001_squashed_0003_auto_20220402_1634"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recentsearch",
            options={},
        ),
        migrations.AddIndex(
            model_name="recentsearch",
            index=models.Index(
                fields=["user", "sort_order"], name="search_rece_user_id_3a69cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recentsearch",
            index=models.Index(
                fields=["user", "search_text"], name="search_rece_user_id_da28b6_idx"
            ),
        ),
    ]
