# Generated by Django 5.2.8 on 2025-11-26 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0004_alter_recentsearch_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recentsearch",
            options={"ordering": ["sort_order", "-created"]},
        ),
    ]
