"""
URL configuration for the Music app.
"""

from django.urls import path

from . import views

app_name = "music"

urlpatterns = [
    path(
        route="create/",
        view=views.SongCreateView.as_view(),
        name="create"
    ),
    path(
        route="search_artist",
        view=views.search_artists,
        name="search_artists"
    ),
    path(
        route="update/<uuid:uuid>/",
        view=views.SongUpdateReactView.as_view(),
        name="update"
    ),
    path(
        route="song_form_ajax/<uuid:uuid>/",
        view=views.SongFormAjaxView.as_view(),
        name="song_form_ajax"
    ),
    path(
        route="album_list",
        view=views.AlbumListView.as_view(),
        name="album_list"
    ),
    path(
        route="album/<uuid:uuid>/",
        view=views.AlbumDetailView.as_view(),
        name="album_detail"
    ),
    path(
        route="album_update/<uuid:uuid>/",
        view=views.AlbumUpdateView.as_view(),
        name="album_update"
    ),
    path(
        route="artist/<uuid:uuid>/",
        view=views.ArtistDetailView.as_view(),
        name="artist_detail"
    ),
    path(
        route="recent_songs",
        view=views.RecentSongsListView.as_view(),
        name="recent_songs"
    ),
    path(
        route="mark_song_as_listened_to/<uuid:uuid>",
        view=views.mark_song_as_listened_to,
        name="mark_song_as_listened_to"
    ),
    path(
        route="tag/",
        view=views.SearchTagListView.as_view(),
        name="search_tag"
    ),
    path(
        route="",
        view=views.music_list,
        name="list"
    ),
    path(
        route="get_song_id3_info",
        view=views.get_song_id3_info,
        name="get_song_id3_info"
    ),
    path(
        route="delete/<uuid:uuid>/",
        view=views.MusicDeleteView.as_view(),
        name="delete"
    ),
    path(
        route="playlist_detail/<uuid:uuid>",
        view=views.PlaylistDetailView.as_view(),
        name="playlist_detail"
    ),
    path(
        route="playlist_create",
        view=views.CreatePlaylistView.as_view(),
        name="playlist_create"
    ),
    path(
        route="playlist_update/<uuid:uuid>/",
        view=views.UpdatePlaylistView.as_view(),
        name="playlist_update"
    ),
    path(
        route="get_playlist/<uuid:playlist_uuid>",
        view=views.get_playlist,
        name="get_playlist"
    ),
    path(
        route="delete_playlist/<uuid:uuid>/",
        view=views.PlaylistDeleteView.as_view(),
        name="delete_playlist"
    ),
    path(
        route="sort_playlist",
        view=views.sort_playlist,
        name="sort_playlist"
    ),
    path(
        route="search_playlists/",
        view=views.search_playlists,
        name="search_playlists"
    ),
    path(
        route="add_to_playlist/",
        view=views.add_to_playlist,
        name="add_to_playlist"
    ),
    path(
        route="update_artist_image",
        view=views.update_artist_image,
        name="update_artist_image"
    ),
    path(
        route="missing_artist_images",
        view=views.missing_artist_images,
        name="missing_artist_images"
    ),
    path(
        route="dupe_song_checker",
        view=views.dupe_song_checker,
        name="dupe_song_checker"
    ),
    path(
        route="recent_albums/<int:page_number>/",
        view=views.recent_albums,
        name="recent_albums"
    ),
    path(
        route="set_song_rating",
        view=views.set_song_rating,
        name="set_song_rating"
    ),
    path(
        route="create_album",
        view=views.CreateAlbumView.as_view(),
        name="create_album"
    ),
    path(
        route="scan_album_from_zipfile",
        view=views.scan_album_from_zipfile,
        name="scan_album_from_zipfile"
    ),
    path(
        route="add_album_from_zipfile",
        view=views.add_album_from_zipfile,
        name="add_album_from_zipfile"
    ),
]
