# Generated by Django 5.2.11 on 2026-03-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0001_initial"),
        ("tag", "0019_taghabit_tag_habits"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="tags",
            field=models.ManyToManyField(blank=True, to="tag.tag"),
        ),
    ]
