# Generated by Django 5.2.11 on 2026-03-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0002_replace_unique_together_with_constraints"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="habitlog",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="habitlog",
            constraint=models.UniqueConstraint(
                fields=("habit", "date"), name="unique_habit_date"
            ),
        ),
    ]
