# Generated by Django 5.2.11 on 2026-03-08 15:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0003_alter_habitlog_unique_together_and_more"),
        ("tag", "0020_replace_unique_together_with_constraints"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={},
        ),
        migrations.AddIndex(
            model_name="habit",
            index=models.Index(
                fields=["user", "-end_date"], name="habit_habit_user_id_92a630_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="habitlog",
            index=models.Index(
                fields=["habit", "-date"], name="habit_habit_habit_i_287d2c_idx"
            ),
        ),
    ]
