# Generated by Django 5.2.11 on 2026-03-08 17:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0005_alter_habit_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habitlog",
            name="value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
