# Generated by Django 5.2.11 on 2026-03-08 18:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0006_alter_habitlog_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="end_date",
            field=models.DateField(
                blank=True,
                help_text="Date habit tracking ended; blank means still active",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="purpose",
            field=models.TextField(
                blank=True, help_text="Why you are tracking this habit"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="start_date",
            field=models.DateField(help_text="Date habit tracking begins"),
        ),
        migrations.AlterField(
            model_name="habitlog",
            name="value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Optional numeric measurement (e.g. minutes, reps, miles)",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
