# Generated by Django 5.2.13 on 2026-05-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0007_alter_habit_end_date_alter_habit_purpose_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="unit",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Unit shown alongside numeric log values, e.g. 'mg', 'IU', 'caps'",
                max_length=16,
            ),
        ),
    ]
