# Generated by Django 5.2.15 on 2026-07-28 15:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0008_habit_unit"),
    ]

    operations = [
        migrations.CreateModel(
            name="HabitNote",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("date", models.DateField()),
                ("note", models.TextField()),
                (
                    "habit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="habit.habit",
                    ),
                ),
            ],
            options={
                "ordering": ("-date", "created"),
                "indexes": [
                    models.Index(
                        fields=["habit", "-date"], name="habit_habit_habit_i_7b7333_idx"
                    )
                ],
            },
        ),
    ]
