# Generated by Django 5.2.7 on 2025-10-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitness", "0024_alter_data_duration_alter_data_reps"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="muscle",
            field=models.ManyToManyField(
                related_name="exercises",
                through="fitness.ExerciseMuscle",
                to="fitness.muscle",
            ),
        ),
    ]
