# Generated by Django 5.2.11 on 2026-03-04 16:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitness", "0025_alter_exercise_muscle"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="exercisemuscle",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="exerciseuser",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="exercisemuscle",
            constraint=models.UniqueConstraint(
                fields=("exercise", "muscle"), name="unique_exercise_muscle"
            ),
        ),
        migrations.AddConstraint(
            model_name="exerciseuser",
            constraint=models.UniqueConstraint(
                fields=("user", "exercise"), name="unique_user_exercise"
            ),
        ),
    ]
