# Generated by Django 5.2.14 on 2026-06-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitness", "0026_replace_unique_together_with_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="has_reps",
            field=models.BooleanField(default=True),
        ),
    ]
