# Generated by Django 5.2.11 on 2026-02-18 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0001_initial"),
        ("tag", "0018_tag_check_name_is_lowercase"),
    ]

    operations = [
        migrations.CreateModel(
            name="TagHabit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.IntegerField(default=1)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "habit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="habit.habit"
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tag.tag"
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order",),
                "unique_together": {("tag", "habit")},
            },
        ),
        migrations.AddField(
            model_name="tag",
            name="habits",
            field=models.ManyToManyField(through="tag.TagHabit", to="habit.habit"),
        ),
    ]
