# Generated by Django 5.2.11 on 2026-03-05 16:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmark", "0011_alter_bookmark_note"),
        ("habit", "0002_replace_unique_together_with_constraints"),
        ("tag", "0019_taghabit_tag_habits"),
        ("todo", "0015_alter_todo_priority"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tag",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="tagbookmark",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="taghabit",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="tagtodo",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                fields=("name", "user"), name="tag_unique_name_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="tagbookmark",
            constraint=models.UniqueConstraint(
                fields=("tag", "bookmark"), name="tagbookmark_unique_tag_bookmark"
            ),
        ),
        migrations.AddConstraint(
            model_name="taghabit",
            constraint=models.UniqueConstraint(
                fields=("tag", "habit"), name="taghabit_unique_tag_habit"
            ),
        ),
        migrations.AddConstraint(
            model_name="tagtodo",
            constraint=models.UniqueConstraint(
                fields=("tag", "todo"), name="tagtodo_unique_tag_todo"
            ),
        ),
    ]
