name: Run Pytest

on:
  push:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: bordercore
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        ports:
          - 5432:5432
    env:
      PYTHONPATH: $PYTHONPATH:.:bordercore
      DJANGO_SETTINGS_MODULE: config.settings.dev
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        python-version: "3.13"

    - name: Install dependencies
      run: uv sync --group dev

    - name: Run mypy
      run: |
        uv run mypy --config-file pyproject.toml bordercore/

    - name: Run tests
      env:
        SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        DJANGO_LOG_DIR: ${{ runner.temp }}
        DATABASE_HOST: localhost
        DATABASE_USER: postgres
        DATABASE_PASSWORD: postgres
      run: |
        uv run pytest -m "not data_quality and not functional" ./bordercore/ -v -n auto
