# Generated by Django 5.2.11 on 2026-03-08 15:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0009_alter_playlist_size_alter_song_length"),
        ("tag", "0020_replace_unique_together_with_constraints"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="song",
            options={},
        ),
        migrations.AddIndex(
            model_name="song",
            index=models.Index(
                fields=["user", "album"], name="music_song_user_id_b5f356_idx"
            ),
        ),
    ]
