# Generated by Django 5.2.11 on 2026-03-08 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0010_alter_song_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="song",
            options={"ordering": ("-modified", "-created")},
        ),
    ]
