# Generated by Django 5.2.11 on 2026-03-08 17:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0012_deduplicate_songs"),
        ("tag", "0020_replace_unique_together_with_constraints"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="song",
            constraint=models.UniqueConstraint(
                fields=("title", "artist", "album", "user"),
                name="unique_song_title_artist_album_user",
                nulls_distinct=False,
            ),
        ),
    ]
