# Generated by Django 5.2.11 on 2026-03-08 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0013_song_unique_song_title_artist_album_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="compilation",
            field=models.BooleanField(
                default=False, help_text="True if this is a various-artists compilation"
            ),
        ),
        migrations.AlterField(
            model_name="album",
            name="original_release_year",
            field=models.IntegerField(
                help_text="Year the album was originally released, if this is a reissue",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="length",
            field=models.PositiveIntegerField(
                blank=True, help_text="Duration in seconds", null=True
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="original_album",
            field=models.TextField(
                help_text="Album this song first appeared on, if different from current",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="original_year",
            field=models.IntegerField(
                help_text="Original release year, if different from current album year",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="source",
            field=models.ForeignKey(
                help_text="Where the song was acquired (e.g. Amazon, Bandcamp)",
                on_delete=django.db.models.deletion.PROTECT,
                to="music.songsource",
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="times_played",
            field=models.PositiveIntegerField(
                default=0, help_text="Lifetime play count, incremented by listen_to()"
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="track",
            field=models.PositiveIntegerField(
                help_text="Track number on the album", null=True
            ),
        ),
    ]
