# Generated by Django 5.2.11 on 2026-03-12 15:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0015_fix_playlistitem_sort_order"),
        ("tag", "0020_replace_unique_together_with_constraints"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="song",
            name="unique_song_title_artist_album_user",
        ),
        migrations.AddConstraint(
            model_name="song",
            constraint=models.UniqueConstraint(
                condition=models.Q(("album__isnull", False)),
                fields=("title", "artist", "album", "user"),
                name="unique_song_title_artist_album_user",
            ),
        ),
    ]
